---
- name: "Pull mysql image"
  docker_image:
    name: 'actency/docker-mysql-replication'
    tag: '5.7'

- name: Mysql Master
  community.docker.docker_container:
    name: mysql-container
    image: actency/docker-mysql-replication:5.7
    state: started
    ports: 
      - "3306:3306"
    tty: true
    detach: 
    volumes:
      - "/data/mastermysql:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      REPLICATION_USER: "{{ replication_user }}"
      REPLICATION_PASSWORD: "{{ replication_password }}"
  

- name: Task MySQL Finished
  debug:
    msg: Task MySQL Finished
...